name: Deploy Zidsa Theme

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Zidsa
        uses: Younis-Ahmed/zidsa-action@v0.2.5
        with:
          THEME_ID: ${{ secrets.THEME_ID }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}